repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg] # 커밋 메시지 작성 시 commitlint를 실행하도록 설정
        additional_dependencies: ["@commitlint/config-conventional"] # commit 규격으로 Conventional Commits을 사용함을 설정
